export default [
  {
    givenName: "Carl",
    surname: "Barnes",
    gender: "Male",
    age: "19",
    email: "c.barnes@randatmail.com",
    phone: "473-3165-08",
    occupation: "Mechanic",
    maritalStatus: "Married",
  },
  {
    givenName: "Alexia",
    surname: "Bailey",
    gender: "Female",
    age: "21",
    email: "a.bailey@randatmail.com",
    phone: "398-6893-75",
    occupation: "Scientist",
    maritalStatus: "Single",
  },
  {
    givenName: "Savana",
    surname: "Miller",
    gender: "Female",
    age: "23",
    email: "s.miller@randatmail.com",
    phone: "996-5188-26",
    occupation: "Veterinarian",
    maritalStatus: "Married",
  },
  {
    givenName: "Sarah",
    surname: "Clark",
    gender: "Female",
    age: "19",
    email: "s.clark@randatmail.com",
    phone: "676-5424-31",
    occupation: "Firefighter",
    maritalStatus: "Married",
  },
  {
    givenName: "Paul",
    surname: "Elliott",
    gender: "Male",
    age: "20",
    email: "p.elliott@randatmail.com",
    phone: "367-1125-99",
    occupation: "Actor",
    maritalStatus: "Married",
  },
  {
    givenName: "Kelsey",
    surname: "Robinson",
    gender: "Female",
    age: "27",
    email: "k.robinson@randatmail.com",
    phone: "638-9745-22",
    occupation: "Meteorologist",
    maritalStatus: "Married",
  },
  {
    givenName: "Emma",
    surname: "Moore",
    gender: "Female",
    age: "26",
    email: "e.moore@randatmail.com",
    phone: "106-0420-49",
    occupation: "Baker",
    maritalStatus: "Married",
  },
  {
    givenName: "Lenny",
    surname: "Wright",
    gender: "Male",
    age: "29",
    email: "l.wright@randatmail.com",
    phone: "150-9959-00",
    occupation: "Accountant",
    maritalStatus: "Single",
  },
  {
    givenName: "Heather",
    surname: "Douglas",
    gender: "Female",
    age: "26",
    email: "h.douglas@randatmail.com",
    phone: "312-0891-87",
    occupation: "Mechanic",
    maritalStatus: "Single",
  },
  {
    givenName: "Chloe",
    surname: "Nelson",
    gender: "Female",
    age: "27",
    email: "c.nelson@randatmail.com",
    phone: "778-6299-15",
    occupation: "Engineer",
    maritalStatus: "Single",
  },
  {
    givenName: "Ryan",
    surname: "Farrell",
    gender: "Male",
    age: "28",
    email: "r.farrell@randatmail.com",
    phone: "148-4180-89",
    occupation: "Biochemist",
    maritalStatus: "Married",
  },
  {
    givenName: "Edwin",
    surname: "Harrison",
    gender: "Male",
    age: "28",
    email: "e.harrison@randatmail.com",
    phone: "960-2031-00",
    occupation: "Engineer",
    maritalStatus: "Married",
  },
  {
    givenName: "Adison",
    surname: "Robinson",
    gender: "Male",
    age: "22",
    email: "a.robinson@randatmail.com",
    phone: "315-9946-03",
    occupation: "Architect",
    maritalStatus: "Married",
  },
  {
    givenName: "Belinda",
    surname: "Hunt",
    gender: "Female",
    age: "30",
    email: "b.hunt@randatmail.com",
    phone: "969-2602-62",
    occupation: "Interpreter",
    maritalStatus: "Married",
  },
  {
    givenName: "Tiana",
    surname: "Harris",
    gender: "Female",
    age: "18",
    email: "t.harris@randatmail.com",
    phone: "302-1202-96",
    occupation: "Biochemist",
    maritalStatus: "Married",
  },
  {
    givenName: "Amanda",
    surname: "Reed",
    gender: "Female",
    age: "23",
    email: "a.reed@randatmail.com",
    phone: "116-9662-07",
    occupation: "Jeweller",
    maritalStatus: "Single",
  },
  {
    givenName: "Victor",
    surname: "Edwards",
    gender: "Male",
    age: "23",
    email: "v.edwards@randatmail.com",
    phone: "055-9550-14",
    occupation: "Astronomer",
    maritalStatus: "Married",
  },
  {
    givenName: "David",
    surname: "Clark",
    gender: "Male",
    age: "28",
    email: "d.clark@randatmail.com",
    phone: "585-2948-60",
    occupation: "Architect",
    maritalStatus: "Single",
  },
  {
    givenName: "Maddie",
    surname: "Edwards",
    gender: "Female",
    age: "27",
    email: "m.edwards@randatmail.com",
    phone: "712-4993-55",
    occupation: "Journalist",
    maritalStatus: "Married",
  },
  {
    givenName: "Thomas",
    surname: "Cameron",
    gender: "Male",
    age: "26",
    email: "t.cameron@randatmail.com",
    phone: "702-5627-00",
    occupation: "Graphic Designer",
    maritalStatus: "Married",
  },
  {
    givenName: "Maya",
    surname: "Perkins",
    gender: "Female",
    age: "18",
    email: "m.perkins@randatmail.com",
    phone: "557-0333-97",
    occupation: "Salesman",
    maritalStatus: "Single",
  },
  {
    givenName: "Annabella",
    surname: "Dixon",
    gender: "Female",
    age: "24",
    email: "a.dixon@randatmail.com",
    phone: "293-5981-60",
    occupation: "Jeweller",
    maritalStatus: "Married",
  },
  {
    givenName: "Naomi",
    surname: "Williams",
    gender: "Female",
    age: "25",
    email: "n.williams@randatmail.com",
    phone: "718-5633-04",
    occupation: "Pharmacist",
    maritalStatus: "Single",
  },
  {
    givenName: "Isabella",
    surname: "Richards",
    gender: "Female",
    age: "28",
    email: "i.richards@randatmail.com",
    phone: "529-1259-26",
    occupation: "Chef",
    maritalStatus: "Married",
  },
  {
    givenName: "Adam",
    surname: "Montgomery",
    gender: "Male",
    age: "25",
    email: "a.montgomery@randatmail.com",
    phone: "080-4035-41",
    occupation: "Firefighter",
    maritalStatus: "Single",
  },
  {
    givenName: "Alfred",
    surname: "Nelson",
    gender: "Male",
    age: "26",
    email: "a.nelson@randatmail.com",
    phone: "698-0271-39",
    occupation: "Actor",
    maritalStatus: "Married",
  },
  {
    givenName: "Miller",
    surname: "Hill",
    gender: "Male",
    age: "23",
    email: "m.hill@randatmail.com",
    phone: "526-9584-08",
    occupation: "Producer",
    maritalStatus: "Married",
  },
  {
    givenName: "Dominik",
    surname: "Andrews",
    gender: "Male",
    age: "20",
    email: "d.andrews@randatmail.com",
    phone: "521-0855-24",
    occupation: "Cook",
    maritalStatus: "Married",
  },
  {
    givenName: "Alisa",
    surname: "Murphy",
    gender: "Female",
    age: "19",
    email: "a.murphy@randatmail.com",
    phone: "118-2191-60",
    occupation: "Baker",
    maritalStatus: "Single",
  },
  {
    givenName: "Darcy",
    surname: "Smith",
    gender: "Female",
    age: "23",
    email: "d.smith@randatmail.com",
    phone: "817-2072-00",
    occupation: "Aeroplane Pilot",
    maritalStatus: "Married",
  },
  {
    givenName: "Jessica",
    surname: "Murray",
    gender: "Female",
    age: "24",
    email: "j.murray@randatmail.com",
    phone: "770-0571-37",
    occupation: "Botanist",
    maritalStatus: "Married",
  },
  {
    givenName: "George",
    surname: "Jones",
    gender: "Male",
    age: "21",
    email: "g.jones@randatmail.com",
    phone: "183-6335-88",
    occupation: "Auditor",
    maritalStatus: "Single",
  },
  {
    givenName: "Stuart",
    surname: "Johnston",
    gender: "Male",
    age: "21",
    email: "s.johnston@randatmail.com",
    phone: "037-3038-93",
    occupation: "Interpreter",
    maritalStatus: "Single",
  },
  {
    givenName: "Aston",
    surname: "Harrison",
    gender: "Male",
    age: "27",
    email: "a.harrison@randatmail.com",
    phone: "331-3299-14",
    occupation: "Interpreter",
    maritalStatus: "Single",
  },
  {
    givenName: "Roman",
    surname: "Crawford",
    gender: "Male",
    age: "29",
    email: "r.crawford@randatmail.com",
    phone: "288-2312-08",
    occupation: "Lecturer",
    maritalStatus: "Married",
  },
  {
    givenName: "Antony",
    surname: "Martin",
    gender: "Male",
    age: "28",
    email: "a.martin@randatmail.com",
    phone: "316-3337-88",
    occupation: "Economist",
    maritalStatus: "Single",
  },
  {
    givenName: "Lyndon",
    surname: "Richardson",
    gender: "Male",
    age: "23",
    email: "l.richardson@randatmail.com",
    phone: "552-4936-84",
    occupation: "Lecturer",
    maritalStatus: "Married",
  },
  {
    givenName: "Lucia",
    surname: "Richards",
    gender: "Female",
    age: "22",
    email: "l.richards@randatmail.com",
    phone: "700-8566-90",
    occupation: "Lawer",
    maritalStatus: "Single",
  },
  {
    givenName: "Rafael",
    surname: "Spencer",
    gender: "Male",
    age: "24",
    email: "r.spencer@randatmail.com",
    phone: "913-2760-77",
    occupation: "Chemist",
    maritalStatus: "Married",
  },
  {
    givenName: "Jordan",
    surname: "Craig",
    gender: "Male",
    age: "19",
    email: "j.craig@randatmail.com",
    phone: "909-6565-36",
    occupation: "Agronomist",
    maritalStatus: "Single",
  },
];
